### PR TITLE
doc: improve readability of directory spec

### LINKED ISSUE #220: Clarify LibEx directory on Windows
The [directory structure spec](https://github.com/notaryproject/notation/blob/main/specs/directory.md#system-level) calls out LibEx files to be placed in the root of `%ProgramFiles%`.
Windows uses nested folders to isolate binaries and config specific to each executable. This includes configuration as well.

This spec seems to call ou BIN is under a subfolder, but LIBEXEC and CONFIG are not.

| Directory | Unix           | Windows                       | Darwin                         |
| --------- | -------------- | ----------------------------- | ------------------------------ |
| `BIN`     | `/usr/bin`     | `%ProgramFiles%/notation/bin` | `/usr/local/bin`               |
| `LIBEXEC` | `/usr/libexec` | `%ProgramFiles%`              | `/usr/local/lib`               |
| `CONFIG`  | `/etc`         | `%ProgramData%`               | `/Library/Application Support` |

This issue clarifies that all notation components should be under a sub-directory on Windows, not just the BIN.

Suggesting the following:

| Directory | Unix           | Windows                       | Darwin                         |
| --------- | -------------- | ----------------------------- | ------------------------------ |
| `BIN`     | `/usr/bin`     | `%ProgramFiles%/notation/bin` | `/usr/local/bin`               |
| `LIBEXEC` | `/usr/libexec` | `%ProgramFiles%/notation/bin` | `/usr/local/lib`               |
| `CONFIG`  | `/etc`         | `%ProgramData%/notation/`     | `/Library/Application Support` |

The [Windows examples](https://github.com/notaryproject/notation/blob/main/specs/directory.md#windows) section seems to imply these are sub directories, so it looks like the above just needs a bit more consistency across platforms as each platform stores notation in a sub-directory.

### PR DESCRIPTION
**Pull request by shizhMSFT**
Improve readability of directory spec without changing the underlying directory structures.

Resolves #220
Signed-off-by: Shiwei Zhang <shizh@microsoft.com>

### CODE REVIEW

**Review by yizha1 — COMMENTED** [review]
LGTM

**Review by FeynmanZhou — APPROVED** [review]
LGTM

**Review by gokarnm — APPROVED** [review]
LGTM! @SteveLasker @NiazFK this is ready to be merged.

**Comment by JeyJeyGao** [comment]
LGTM

**Pull request merged**
