### PR TITLE
Update deps links for notation-go

### PR DESCRIPTION
**Pull request by dtzar**
This is to allow the client to utilize the latest version of the now renamed notation-go library. It will need another release on main to finalize.

### CODE REVIEW

**Review by SteveLasker — APPROVED** [review]
LGTM

**Comment by SteveLasker** [comment]
cc @qmuntal

**Review by qmuntal — APPROVED** [review]

**Comment by dtzar** [comment]
FWIW - I manually reverted that version of the go-lang/jwt package to try and change as minimal as possible but obviously it is required.  From 4.1.x --> 4.3.x nothing seems earth shattering in the changelog...

**Comment by dtzar** [comment]
@SteveLasker Once you manually approve the build job (again) it should pass and we can merge.  After that I'll be over the "first-time contributor" configuration you have to run build jobs. 🎉

**Pull request merged**
