### PR TITLE
docs: fix broken links

### PR DESCRIPTION
**Pull request by suzuki-shunsuke**
The link is broken.

https://notaryproject.dev/docs/quickstart/

image

> The page that you requested doesn't exist.
> 
> Check the URL's spelling.
> 
> If you think that the page should exist, [create an issue.](https://github.com/notaryproject/notaryproject.dev/issues/new?title=Unexpected%20page-not-found%20error&body=URL%3A%20%0AExpected%20page%3A%20)

So I fixed the link.

https://notaryproject.dev/docs/quickstart-guides/quickstart/

### CODE REVIEW

**Comment by suzuki-shunsuke** [comment]
I found three broken links.

I confirmed that all broken links are fixed with [lychee](https://github.com/lycheeverse/lychee).

```console
$ git ls-files | grep -E "\.md$" | xargs lychee
⠉ 39/59 ETA 1s █████████████░░░░░░░ ✔ [200] https://docs.microsoft.com/azure/container-registry/container-registry-tutorial-sign-b
⠉ 40/59 ETA 1s █████████████░░░░░░░ ✔ [200] https://github.com/notaryproject/notaryproject/blob/main/specs/trust-store-trust-polic
  59/59 ETA 0s ████████████████████ Finished extracting links                                                                     
🔍 59 Total ✅ 59 OK 🚫 0 Errors
```

**Review by FeynmanZhou — APPROVED** [review]
LGTM

**Review by shizhMSFT — APPROVED** [review]
LGTM

**Review by Two-Hearts — APPROVED** [review]
LGTM

**Review by priteshbandi — APPROVED** [review]
LGTM

**Pull request merged**
