### PR TITLE
bump: bump up notation-go v1.1.1 and other dependencies

### PR DESCRIPTION
**Pull request by JeyJeyGao**
Signed-off-by: Junjie Gao <junjiegao@microsoft.com>

### CODE REVIEW

**Review by shizhMSFT — DISMISSED** [review]
LGTM

**Review by Two-Hearts — CHANGES_REQUESTED** [review]
We should also update the dependencies in `test/e2e`. They are `test/e2e/go.mod` and `test/e2e/plugin/go.mod`.

**Review by priteshbandi — DISMISSED** [review]
LGTM

**Comment by JeyJeyGao** [comment]
> We should also update the dependencies in `test/e2e`. They are `test/e2e/go.mod` and `test/e2e/plugin/go.mod`.

Updated.

**Comment by Two-Hearts** [comment]
LGTM, but waiting for the DCO status.

**Review by Two-Hearts — APPROVED** [review]
LGTM

**Review by priteshbandi — APPROVED** [review]
LGTM

**Pull request merged**
