### PR TITLE
Add Junjie Gao as notation maintainer

### PR DESCRIPTION
**Pull request by yizha1**
Add Junjie Gao (@JeyJeyGao) as a seed maintainer of `notation` based on [their](https://github.com/notaryproject/notation/commits?author=JeyJeyGao) activity as per - https://github.com/notaryproject/notation/issues/514

Signed-off-by: Yi Zha <yizha1@microsoft.com>

### CODE REVIEW

**Review by priteshbandi — APPROVED** [review]
LGTM but IANAM

**Review by shizhMSFT — APPROVED** [review]
LGTM

**Review by toddysm — APPROVED** [review]
LGTM but IANAM

**Comment by SteveLasker** [comment]
+1 for adding @JeyJeyGao 
However, this PR also removes the @notaryproject/notation-maintainers list
Suggest we treat these as separate PRs, reviewing Junjie as an added maintainer, and a separate PR to convert the teams reference of @notaryproject/notation-maintainers to the individuals in that list.

**Review by patrickzheng200 — APPROVED** [review]
LGTM but IANAM

**Review by binbin-li — APPROVED** [review]
lgtm

**Review by vaninrao10 — APPROVED** [review]
LGTM

**Review by vaninrao10 — APPROVED** [review]
LGTM

**Comment by gokarnm** [comment]
LGTM

**Review by gokarnm — APPROVED** [review]

**Review by gokarnm — APPROVED** [review]
LGTM but IANAM

**Comment by iamsamirzon** [comment]
LGTM but IANAM

**Review by iamsamirzon — APPROVED** [review]

**Comment by yizha1** [comment]
Close as aggregated PR https://github.com/notaryproject/notation/pull/542 was merged

**Pull request closed without merging**
