### PR TITLE
blob upload "Location" can be relative or absolute

### PR DESCRIPTION
**Pull request by rchincha**
Signed-off-by: Ramkumar Chinchani <rchincha@cisco.com>

### CODE REVIEW

**Comment by SteveLasker** [comment]
@shizhMSFT :eyes: ^?

**Review by SteveLasker — APPROVED** [review]
Thanks, @rchincha for taking the time to submit this PR
LGTM

**Comment by shizhMSFT** [comment]
Thank @rchincha for finding out this issue and contributing the fix.

This is an known issue being tracked at #114. A fix #115 has been proposed to address this issue. /cc @SteveLasker

**Comment by rchincha** [comment]
Appears to be fixed with commit:

```
commit ffc784444b46a06730019f7ff10a81c3aa1c857b                                                                                                                             Author: Shiwei Zhang <shizh@microsoft.com>                                                                                                                                  Date:   Sat Oct 30 10:26:13 2021 +0800                                                                                                                                                                                                                                                                                                                      fix location (#115)                                                                                                                                                                                                                                                                                                                                     Signed-off-by: Shiwei Zhang <shizh@microsoft.com>

**Pull request closed without merging**
