### PR TITLE
Added CODEOWNERS and MAINTAINERS files

### PR DESCRIPTION
**Pull request by toddysm**
Signed-off-by: Toddy Mladenov <toddysm@gmail.com>

This PR combines all the changes from the following PRs for updating the maintainers for *notaryproject/notation* sub-project:
[Add Junjie Gao](https://github.com/notaryproject/notation/pull/532)
[Add Milind Gokarn](https://github.com/notaryproject/notation/pull/523)
[Add PatrickZheng](https://github.com/notaryproject/notation/pull/531)
[Add Pritesh Bandi](https://github.com/notaryproject/notation/pull/524)
[Add Rakesh Gariganti](https://github.com/notaryproject/notation/pull/522)
[Add Shiwei Zhang](https://github.com/notaryproject/notation/pull/530)

To keep the balance of maintainers, I removed:
[Add Yi Zha](https://github.com/notaryproject/notation/pull/515)

The proposal is to abandon the above PRs and merge only this one.

### CODE REVIEW

**Comment by toddysm** [comment]
Linking the related PRs: #515 #522 #523 #524 #530 #531 #532

**Review by vaninrao10 — CHANGES_REQUESTED** [review]
In Maintainers file Rakesh Gokarn <garigant@amazon.com> (@rgnote) need to be changed to Rakesh Gariganti <garigant@amazon.com> (@rgnote)

**Review by vaninrao10 — APPROVED** [review]
LGTM

**Comment by toddysm** [comment]
Linking the issu #514

**Review by priteshbandi — APPROVED** [review]
LGTM but IANAM

**Review by JeyJeyGao — APPROVED** [review]
LGTM but IANAM

**Review by shizhMSFT — APPROVED** [review]
LGTM

**Review by patrickzheng200 — APPROVED** [review]
LGTM but IANAM

**Review by yizha1 — APPROVED** [review]
LGTM but IANAM

**Review by FeynmanZhou — APPROVED** [review]
LGTM but IANAM

**Review by NiazFK — APPROVED** [review]
LGTM

**Review by SteveLasker — APPROVED** [review]
LGTM
Welcome new maintainers!

**Comment by SteveLasker** [comment]
Pinging @justincormack for a majority vote.

**Review by gokarnm — APPROVED** [review]
LGTM but IANAM

**Review by iamsamirzon — APPROVED** [review]

**Review by justincormack — APPROVED** [review]

**Pull request merged**
