### PR TITLE
Add Shiwei Zhang as notation maintainer

### PR DESCRIPTION
**Pull request by yizha1**
Add Shiwei Zhang (@shizhMSFT) as a seed maintainer of `notation` based on [their](https://github.com/notaryproject/notation/commits?author=shizhMSFT) activity as per - https://github.com/notaryproject/notation/issues/514

Signed-off-by: Yi Zha <yizha1@microsoft.com>

### CODE REVIEW

**Review by priteshbandi — APPROVED** [review]
LGTM but IANAM

**Comment by iamsamirzon** [comment]
LGTM but IANAM

**Review by toddysm — APPROVED** [review]
LGTM but IANAM

**Comment by SteveLasker** [comment]
+1 for adding @shizhMSFT, although he's already in the [
notation-sub-group-maintainers](https://github.com/orgs/notaryproject/teams/notation-sub-group-maintainers) teams list

Suggest we treat these as separate PRs, reviewing the addition of individuals, and a separate PR to convert the teams reference of @notaryproject/notation-maintainers to the individuals in that list.

**Review by patrickzheng200 — APPROVED** [review]
LGTM but IANAM

**Review by JeyJeyGao — APPROVED** [review]
LGTM but IANAM

**Review by binbin-li — APPROVED** [review]
LGTM but IANAM

**Review by vaninrao10 — APPROVED** [review]
LGTM

**Review by gokarnm — APPROVED** [review]
LGTM but IANAM

**Review by iamsamirzon — APPROVED** [review]

**Comment by yizha1** [comment]
Close as aggregated PR https://github.com/notaryproject/notation/pull/542 was merged

**Pull request closed without merging**
