### PR TITLE
Correct broken link to quick start guide

### PR DESCRIPTION
**Pull request by rcrozean**
Similarly to https://github.com/notaryproject/notaryproject.dev/issues/360, 
I attempted to follow the link in the README.md for the quick start guide and discovered the broken link. Linking to the official page.

URL: https://notaryproject.dev/docs/quickstart/
Expected page: https://notaryproject.dev/docs/quickstart-guides/quickstart-sign-image-artifact/

### CODE REVIEW

**Review by Two-Hearts — APPROVED** [review]
LGTM

**Review by FeynmanZhou — APPROVED** [review]
LGTM

**Comment by priteshbandi** [comment]
@rcrozean can you please sign your commit? 

https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification

**Comment by rcrozean** [comment]
Commit signed!

**Pull request merged**
