### PR TITLE
chore: update account info for Patrick Zheng

### PR DESCRIPTION
**Pull request by yizha1**
Resolve https://github.com/notaryproject/.github/issues/27

Signed-off-by: Yi Zha <yizha1@microsoft.com>

### CODE REVIEW

**Review by JeyJeyGao — APPROVED** [review]
LGTM

**Review by JeyJeyGao — APPROVED** [review]
LGTM

**Review by shizhMSFT — APPROVED** [review]
LGTM

**Review by priteshbandi — APPROVED** [review]
LGTM

**Review by toddysm — APPROVED** [review]

**Review by gokarnm — APPROVED** [review]
LGTM

**Comment by shizhMSFT** [comment]
Merging this PR since there is a majority of votes (4 + 1) over 8 eligible maintainers.

**Pull request merged**
