### PR TITLE
Bump version and dependencies for notation alpha.4 release

### PR DESCRIPTION
**Pull request by yizha1**
Bump up version to `v0.11.0-alpha.4` for notation alpha.4 release

Bump up dependencies:

- `notation-core-go` from `v0.1.0-alpha.3.0.20220921054535-009c09a9628e` to `v0.1.0-alpha.4`
- `notation-go` from `v0.10.0-alpha.3.0.20220927020950-2bcfd343f974` to `v0.11.0-alpha.4`

### CODE REVIEW

**Comment by dtzar** [comment]
Why does the 1.19 golang build fail?

**Comment by yizha1** [comment]
> Why does the 1.19 golang build fail?

No, it is due to an interface changed in notation-go. We need notation #365 to be merged. Pritesh is helping to review the PR now.

**Review by shizhMSFT — APPROVED** [review]
LGTM

**Comment by iamsamirzon** [comment]
LGTM

**Pull request merged**
