### PR TITLE
Add Pritesh Bandi as notation maintainer

### PR DESCRIPTION
**Pull request by vaninrao10**
Add Pritesh Bandi as a seed maintainer of Notation based on [their](https://github.com/notaryproject/notation/commits?author=priteshbandi) activity as per - https://github.com/notaryproject/notation/issues/514

Signed-off-by: vaninrao10 <111005862+vaninrao10@users.noreply.github.com>

### CODE REVIEW

**Review by toddysm — APPROVED** [review]
LGTM but IANAM

**Comment by FeynmanZhou** [comment]
LGTM

**Review by FeynmanZhou — APPROVED** [review]
LGTM

**Review by yizha1 — APPROVED** [review]
LGTM

**Review by shizhMSFT — APPROVED** [review]
LGTM

**Comment by SteveLasker** [comment]
+1 to adding @priteshbandi 
Please see comments in #530, #531, #532

**Review by patrickzheng200 — APPROVED** [review]
LGTM but IANAM

**Review by JeyJeyGao — APPROVED** [review]
LGTM but IANAM

**Review by binbin-li — APPROVED** [review]
LGTM but IANAM

**Review by gokarnm — APPROVED** [review]
LGTM but IANAM

**Review by iamsamirzon — APPROVED** [review]

**Comment by yizha1** [comment]
Close as aggregated PR https://github.com/notaryproject/notation/pull/542 was merged

**Pull request closed without merging**
