### PR TITLE
backport: CRL cache with log and E2E tests from `main` to `release-1.3`

### PR DESCRIPTION
**Pull request by Two-Hearts**
This PR backports changes related to crl cache from `main` to `release-1.3` branch.

PRs that's backporting:
- https://github.com/notaryproject/notation/pull/1076
- https://github.com/notaryproject/notation/pull/1078
- https://github.com/notaryproject/notation/pull/1079

This PR targets `release-1.3` branch.

### CODE REVIEW

**Comment by JeyJeyGao** [comment]
It looks like this PR includes #1076, #1078, and #1079.

For #1079, which is the test for the entire CRL feature and not limited to the cache, should we update the PR name to:
> backport: CRL cache and CRL E2E test from main to release-1.3 branch

Also, please mention the PRs that we are backporting in the PR description. Thanks!

**Comment by Two-Hearts** [comment]
> It looks like this PR includes #1076, #1078, and #1079.
> 
> For #1079, which is the test for the entire CRL feature and not limited to the cache, should we update the PR name to:
> 
> > backport: CRL cache and CRL E2E test from main to release-1.3 branch
> 
> Also, please mention the PRs that we are backporting in the PR description. Thanks! @Two-Hearts

@JeyJeyGao Updated.

**Review by JeyJeyGao — APPROVED** [review]
LGTM

**Comment by JeyJeyGao** [comment]
Is it expected that the `test/e2e/go.mod` bump is also included in this PR?

**Comment by Two-Hearts** [comment]
> Is it expected that the `test/e2e/go.mod` bump is also included in this PR?

It was brought in by PR: https://github.com/notaryproject/notation/pull/1079.

**Review by shizhMSFT — APPROVED** [review]
LGTM

**Review by vaninrao10 — APPROVED** [review]
LGTM

**Pull request merged**
