### PR TITLE
build: bump up versions and dependencies

### PR DESCRIPTION
**Pull request by yizha1**
Update:
- Bump up version to `v1.0.0-rc.4`
- Update to `notation-go` `v1.0.0-rc.4`
- Update to `notation-core-go` `v1.0.0-rc.3`

Signed-off-by: Yi Zha <yizha1@microsoft.com>

### CODE REVIEW

**Review by patrickzheng200 — APPROVED** [review]
LGTM

**Review by JeyJeyGao — APPROVED** [review]
LGTM

**Comment by gokarnm** [comment]
LGTM

**Review by priteshbandi — COMMENTED** [review]
We also need to update https://github.com/notaryproject/notation/blob/main/test/e2e/go.mod#L6

**Review by priteshbandi — APPROVED** [review]
LGTM

**Review by JeyJeyGao — APPROVED** [review]
LGTM

**Pull request merged**
