### PR TITLE
test: add unit test for ioutil package

### PR DESCRIPTION
**Pull request by JeyJeyGao**
#516 
Signed-off-by: Junjie Gao <junjiegao@microsoft.com>

### CODE REVIEW

**Comment by patrickzheng200** [comment]
Looks like this PR is just for unit test of a single file. I notice that PR [526](https://github.com/notaryproject/notation/pull/526) does the same thing, and both of the PRs share the same [issue](https://github.com/notaryproject/notation/issues/516) as well. Can we combine them into one PR?

**Comment by shizhMSFT** [comment]
It is OK to have separated PRs.

**Review by shizhMSFT — APPROVED** [review]
LGTM

**Review by priteshbandi — APPROVED** [review]
LGTM

**Pull request merged**
