### PR TITLE
doc: update release management for 1.0

### PR DESCRIPTION
**Pull request by priteshbandi**
update release management for 1.0

### CODE REVIEW

**Review by gokarnm — APPROVED** [review]
LGTM

**Review by rgnote — APPROVED** [review]
LGTM

**Review by Two-Hearts — APPROVED** [review]
LGTM

**Review by yizha1 — APPROVED** [review]
LGTM, I think We will merge this PR after 1.0.0 is released, right?

**Review by FeynmanZhou — APPROVED** [review]
LGTM

**Review by JeyJeyGao — APPROVED** [review]
LGTM

**Review by shizhMSFT — APPROVED** [review]
LGTM

**Pull request merged**
