### PR TITLE
doc: Remove outdated docs

### PR DESCRIPTION
**Pull request by FeynmanZhou**
Remove two outdated docs in Notation CLI as they have been migrated to the Notary website:

- https://notaryproject.dev/docs/tutorials/trust-policy/
- https://notaryproject.dev/docs/how-to/directory-structure/

### CODE REVIEW

**Review by yizha1 — APPROVED** [review]
LGTM

**Review by vaninrao10 — APPROVED** [review]
LGTM

**Comment by FeynmanZhou** [comment]
@shizhMSFT Could you pls help to merge this PR?

**Review by shizhMSFT — APPROVED** [review]
LGTM

**Pull request merged**
