### PR TITLE
Build: bump up versions for rc.1 release

### PR DESCRIPTION
**Pull request by yizha1**
- update to `notation-core-go` `v1.0.0-rc.1`
- update to `notation-go` `v1.0.0-rc.1`
- update Version to `v1.0.0-rc.1`

Signed-off-by: Yi Zha <yizha1@microsoft.com>

### CODE REVIEW

**Review by patrickzheng200 — APPROVED** [review]
LGTM

**Review by shizhMSFT — APPROVED** [review]
LGTM

**Review by vaninrao10 — COMMENTED** [review]
LGTM

**Review by vaninrao10 — APPROVED** [review]
LGTM and this is what we all discussed in our Notary v2 community meeting

**Pull request merged**
