### PR TITLE
bump: update dependencies

### PR DESCRIPTION
**Pull request by Two-Hearts**
Bumping up to notation-go v1.0.1.

<del>Note: The build fails due to E2E test. Therefore, this PR depends on https://github.com/notaryproject/notation/pull/810

As https://github.com/notaryproject/notation/pull/810 is merged, bumping up build is successful now.

### CODE REVIEW

**Comment by JeyJeyGao** [comment]
Looks like we need to update E2E testing?

**Comment by Two-Hearts** [comment]
> Looks like we need to update E2E testing?

Yes, as I mentioned, this is fixed in PR https://github.com/notaryproject/notation/pull/810

**Review by priteshbandi — APPROVED** [review]
LGTM

**Review by JeyJeyGao — APPROVED** [review]
LGTM

**Review by shizhMSFT — APPROVED** [review]
LGTM

**Review by priteshbandi — APPROVED** [review]
LGTM

**Pull request merged**
