### PR TITLE
update verify command to use ts/tp based verification workflow

### PR DESCRIPTION
**Pull request by rgnote**
Signed-off-by: rgnote <5878554+rgnote@users.noreply.github.com>

### CODE REVIEW

**Review by priteshbandi — APPROVED** [review]
LGTM

**Review by shizhMSFT — COMMENTED** [review]
The content of this PR has already been merged to the [dev-rc.1](https://github.com/notaryproject/notation/tree/dev-rc.1) branch by #342 contributed by @binbin-li.

By comparing #342 and #370, this PR has the following items missing:
- Verification config support
- Doc update for `docs/hello-signing.md`
- Print outcomes

**Comment by binbin-li** [comment]
> The content of this PR has already been merged to the [dev-rc.1](https://github.com/notaryproject/notation/tree/dev-rc.1) branch by #342 contributed by @binbin-li.
> 
> By comparing #342 and #370, this PR has the following items missing:
> 
> * Verification config support
> * Doc update for `docs/hello-signing.md`
> * Print outcomes

btw, in https://github.com/notaryproject/notation/pull/359, I added support for both tag and digest. Maybe we need to support it in main as well.

**Comment by dtzar** [comment]
Per the community call, @priteshbandi agreed to close this one in favor of #373 which has this plus additional code.

**Comment by rgnote** [comment]
Closing the PR in favor of https://github.com/notaryproject/notation/pull/373

**Pull request closed without merging**
