### PR TITLE
feat: add notation config environment variable

### LINKED ISSUE #822: Provide environmental variables to set the directory of Notation configuration files and plugin binary
### Is your feature request related to a problem?

There were two environmental variables `NOTATION_LIBEXEC` and `NOTATION_CONFIG` in Notation RC releases that can help users define the directory of Notation configuration files and plugin binaries respectively and pass the values to Notation in advance. See [Notation directory structure for system configuration](https://github.com/notaryproject/notation/blob/v0.11.0-alpha.4/specs/directory.md) for the context. These two environmental variables were removed in RC release. 

After revisiting the setup experience of notation signing and verification, it looks still useful if users want to use Notation in different OS. With these two environmental variables, users can easily define tell Notation where are the directory of Notation plugin binaries, trust policy, and key/cert files in advance. It will simplify signing and verification setup experience without manually retrieving those directory location from different operating system.

### What solution do you propose?

Bring two environmental variables `NOTATION_LIBEXEC` and `NOTATION_CONFIG` back to Notation. Enable users to set the directory of Notation binaries and configuration files respectively by using these two environmental variables.

### What alternatives have you considered?

NA

### Any additional context?

_No response_

### PR DESCRIPTION
**Pull request by JeyJeyGao**
Feat:
- added NOTATION_CONFIG and NOTATION_LIBEXEC environment variables

Test:
- notation sign with NOTATION_LIBEXEC locally
- notation verify with NOTATION_CONFIG locally

Resolves #822 
Signed-off-by: Junjie Gao <junjiegao@microsoft.com>

### CODE REVIEW

**Review by shizhMSFT — APPROVED** [review]
LGTM

**Comment by Two-Hearts** [comment]
Quick question: Is this feat been tested somewhere? Maybe an E2E test case (if possible)?

**Review by Two-Hearts — APPROVED** [review]
LGTM

**Comment by priteshbandi** [comment]
What's the necessity for this? Can't the user utilize XDG_CONFIG_HOME on windows and mac?

**Comment by yizha1** [comment]
@gokarnm @rgnote would you mind reviewing this PR?

**Review by rgnote — APPROVED** [review]
LGTM

**Review by shizhMSFT — APPROVED** [review]
LGTM

**Pull request merged**
