### PR TITLE
doc: add missing username/password options to commands

### PR DESCRIPTION
**Pull request by binbin-li**
### What?

Resovles https://github.com/notaryproject/notation/issues/276

For commands other than `notation login`, we should allow them support `username/password` options even without first-time logging.
Since the `login` command requires `credentialsStore` set up which might be missing for users. So we cannot force users always use `login` to save credentials. Other commands should be able to use the credentials directly from input without `credentialsStore` set up.

Updated commands:
1. sign
2. push
3. pull
4. list
5. cache
6. verify

Signed-off-by: Binbin Li <libinbin@microsoft.com>

### CODE REVIEW

**Review by shizhMSFT — APPROVED** [review]
LGTM

**Review by dtzar — APPROVED** [review]
It would be nice to add to the login section something like: "Once login is completed, then -u -p is no longer required for any notation commands against the registry server authenticated."

**Comment by dtzar** [comment]
@yizha1 - since this is just a doc fix and is now at the 1 week mark, I recommend merging it today before notation release.

**Comment by binbin-li** [comment]
> It would be nice to add to the login section something like: "Once login is completed, then -u -p is no longer required for any notation commands against the registry server authenticated."

Good call, I'll add it.

**Review by shizhMSFT — APPROVED** [review]
LGTM

**Pull request merged**
