### PR TITLE
ci: add zot as a candidate OCI registry

### PR DESCRIPTION
**Pull request by rchincha**
Signed-off-by: Ramkumar Chinchani <rchincha@cisco.com>

### CODE REVIEW

**Comment by rchincha** [comment]
https://github.com/rchincha/notation/pull/26
^ here is a successful run with this PR

**Comment by shizhMSFT** [comment]
Instead of having this kind of "ecosystem" thing, how about using `zot` as the test registry for notation E2E testing? /cc @JeyJeyGao @priteshbandi 

@rchincha I remember that `zot` can serve traffic directly from an OCI layout. Does `zot` support writing to an OCI layout?

**Comment by rchincha** [comment]
> Instead of having this kind of "ecosystem" thing, how about using `zot` as the test registry for notation E2E testing? /cc @JeyJeyGao @priteshbandi
> 
> @rchincha I remember that `zot` can serve traffic directly from an OCI layout. Does `zot` support writing to an OCI layout?

Yes, that is exactly what it is doing when you push signatures to it. Pls. feel free to verify.
Once you give an OCI layout to zot, it takes full control of it (modulo original file/dir perms, etc)

**Comment by JeyJeyGao** [comment]
@rchincha Hi Ramkumar. Thanks for your contribution. The Notation E2E testing framework needs to generate user configurations dynamically, so creating user config and isolation shoud be done in the E2E testing framework. We use Zot registry in the [script](https://github.com/notaryproject/notation/pull/493/files#diff-58692c3c1b72898d92c04a3da34940ccf9c6c8dee931573935885e4aa7d9c7d1) which is an open PR now. Please have a look if you want. I appreciate your suggestion.

**Comment by JeyJeyGao** [comment]
@rchincha The Notation E2E testing framework has been merged with Zot as the default registry. Also adopted your suggestion to support multi-registry! [Related code](https://github.com/notaryproject/notation/blob/main/test/e2e/run.sh)
The function of this PR has been included in the E2E framework, so the PR can be closed. I appreciate your work. If you have any suggestion about our project, please let us know. Thanks!

**Comment by rchincha** [comment]
> @rchincha The Notation E2E testing framework has been merged with Zot as the default registry. Also adopted your suggestion to support multi-registry! [Related code](https://github.com/notaryproject/notation/blob/main/test/e2e/run.sh) The function of this PR has been included in the E2E framework, so the PR can be closed. I appreciate your work. If you have any suggestion about our project, please let us know. Thanks!

Closing this PR as per suggestion.

**Pull request closed without merging**
