### PR TITLE
bump: update notation-go and notation-core-go dependency

### PR DESCRIPTION
**Pull request by priteshbandi**
bump: update notation-go and notation-core-go dependency

### CODE REVIEW

**Review by yizha1 — APPROVED** [review]
LGTM

**Review by patrickzheng200 — APPROVED** [review]
LGTM

**Review by shizhMSFT — APPROVED** [review]
LGTM

**Review by FeynmanZhou — APPROVED** [review]
LGTM.
Let's merge it and trigger the latest dev build release.

**Pull request merged**
