### PR TITLE
build: bump up versions and dependencies

### PR DESCRIPTION
**Pull request by priteshbandi**
bump up versions and dependencies for rc5

### CODE REVIEW

**Comment by Two-Hearts** [comment]
@priteshbandi looks like the build is failed.

**Comment by shizhMSFT** [comment]
You may want to merge #656 and #658 first

**Review by Two-Hearts — APPROVED** [review]
LGTM

**Review by shizhMSFT — APPROVED** [review]
LGTM

**Review by FeynmanZhou — APPROVED** [review]
LGTM

**Review by rgnote — APPROVED** [review]
LGTM

**Review by gokarnm — APPROVED** [review]
LGTM

**Comment by FeynmanZhou** [comment]
We reached the majority of approval. @gokarnm @rgnote Could you pls merge this PR?

**Pull request merged**
